name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # - name: Build
      #   run: npm run build
      - name: Deploy to Netlify
        run: curl -X POST -d {} ${secrets.NETLIFY_HOOK}
        # uses: nwtgck/actions-netlify@v2.0
        # with:
        #   publish-dir: "./dist"
        #   deploy-message: "Deploy from GitHub Actions"
        #   enable-pull-request-comment: false
        #   enable-commit-comment: true
        #   overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
